### ISSUE TITLE
adding feed

### ISSUE THREAD

**Issue by brb91** [plan44/plan44-feed#2]
Hello, I have an issue wen I try to add your feeds repo,

"src-git plan44 ssh://plan44@plan44.ch/home/plan44/sharedgit/plan44-public-feed.git;master"

It's a ssh protocol, and when I try to update it, it want a password

Can you help me,

Thanks,

**Comment by plan44** [comment]
Hi brb91, that URL is an internal one, that's my own staging git server. Is that URL mentioned somewhere? That would be an oversight on my part. Please tell me where so I can correct it.

Just use the github https URL instead:

    src-git plan44 https://github.com/plan44/plan44-feed.git;master

Best Regards,
luz

**Comment by brb91** [comment]
Hi,
That URL is given on the plan44-feed readme.

Thanks a lot ;) ,

Best Regards,

**Comment by brb91** [comment]
When I add this repo and update feeds and install p44-ledchain, nothing appear in menuconfig, this is normal ?

**Comment by plan44** [comment]
Note that you need to prefix kernel modules with `kmod-` for ./scripts/feeds install:

    ./scripts/feeds install kmod-p44-ledchain

After that, it should appear in *Kernel modules* -> *Other modules*

**Comment by plan44** [comment]
BTW: just updated the README.md to include the correct URL ;-)
